package com.example.ui.localization

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिंदी"),
    MARATHI("mr", "Marathi", "मराठी")
}

data class StringsDefinition(
    // App Branding & Navigation
    val appName: String,
    val tagline: String,
    val navHome: String,
    val navSales: String,
    val navExpenses: String,
    val navInventory: String,
    val navInsights: String,
    val navReports: String,
    val navAssistant: String,
    val navSettings: String,

    // Dashboard
    val greetingMorning: String,
    val greetingAfternoon: String,
    val greetingEvening: String,
    val todaySummary: String,
    val revenue: String,
    val expenses: String,
    val profit: String,
    val cashRevenue: String,
    val upiRevenue: String,
    val recentTransactions: String,
    val viewAll: String,
    val noTransactionsYet: String,
    val time7Days: String,
    val time30Days: String,
    val time3Months: String,
    val trendChart: String,

    // Sales
    val salesTitle: String,
    val addSale: String,
    val editSale: String,
    val deleteSale: String,
    val saleAmount: String,
    val productItem: String,
    val paymentMethod: String,
    val cash: String,
    val upi: String,
    val category: String,
    val description: String,
    val date: String,
    val save: String,
    val cancel: String,
    val confirm: String,
    val searchSales: String,

    // Expenses
    val expensesTitle: String,
    val addExpense: String,
    val editExpense: String,
    val deleteExpense: String,
    val expenseAmount: String,
    val searchExpenses: String,
    val rawMaterials: String,
    val transportation: String,
    val rent: String,
    val electricity: String,
    val packaging: String,
    val wages: String,
    val maintenance: String,
    val other: String,

    // Inventory
    val inventoryTitle: String,
    val addProduct: String,
    val editProduct: String,
    val productName: String,
    val quantity: String,
    val unit: String,
    val purchasePrice: String,
    val sellingPrice: String,
    val minStockLevel: String,
    val inStock: String,
    val lowStock: String,
    val outOfStock: String,
    val stockUnits: String,
    val searchProducts: String,
    val adjustStock: String,

    // AI & Predictions
    val insightsTitle: String,
    val cashflowPredictionTitle: String,
    val expectedCashflowNextWeek: String,
    val expectedNextDay: String,
    val inventoryPredictionTitle: String,
    val daysUntilStockout: String,
    val suggestedPurchase: String,
    val financialReadinessTitle: String,
    val financialReadinessSubtitle: String,
    val scoreNeedsImprovement: String,
    val scoreFair: String,
    val scoreGood: String,
    val scoreStrong: String,
    val notEnoughData: String,

    // Voice & Assistant
    val voiceEntryTitle: String,
    val voiceListening: String,
    val voiceSpeakNow: String,
    val voiceUnderstood: String,
    val askAssistant: String,
    val askPlaceholder: String,
    val disclaimerText: String,
    val demoDataActive: String,
    val loadDemoData: String,
    val clearData: String
)

object LocalizedStrings {
    val en = StringsDefinition(
        appName = "Bazaar Saathi",
        tagline = "Smart Finance for Every Small Business",
        navHome = "Home",
        navSales = "Sales",
        navExpenses = "Expenses",
        navInventory = "Inventory",
        navInsights = "Insights",
        navReports = "Reports",
        navAssistant = "AI Saathi",
        navSettings = "Settings",

        greetingMorning = "Good Morning",
        greetingAfternoon = "Good Afternoon",
        greetingEvening = "Good Evening",
        todaySummary = "Today's Summary",
        revenue = "Revenue",
        expenses = "Expenses",
        profit = "Profit",
        cashRevenue = "Cash Revenue",
        upiRevenue = "UPI Revenue",
        recentTransactions = "Recent Transactions",
        viewAll = "View All",
        noTransactionsYet = "No transactions recorded yet. Tap + or use voice to record your first entry!",
        time7Days = "7 Days",
        time30Days = "30 Days",
        time3Months = "3 Months",
        trendChart = "Revenue & Expense Trends",

        salesTitle = "Sales Book",
        addSale = "Add Sale",
        editSale = "Edit Sale",
        deleteSale = "Delete Sale",
        saleAmount = "Sale Amount (₹)",
        productItem = "Product / Item",
        paymentMethod = "Payment Method",
        cash = "Cash",
        upi = "UPI",
        category = "Category",
        description = "Note / Description",
        date = "Date",
        save = "Save",
        cancel = "Cancel",
        confirm = "Confirm",
        searchSales = "Search sales...",

        expensesTitle = "Expense Book",
        addExpense = "Add Expense",
        editExpense = "Edit Expense",
        deleteExpense = "Delete Expense",
        expenseAmount = "Expense Amount (₹)",
        searchExpenses = "Search expenses...",
        rawMaterials = "Raw Materials",
        transportation = "Transportation",
        rent = "Rent",
        electricity = "Electricity",
        packaging = "Packaging",
        wages = "Wages",
        maintenance = "Maintenance",
        other = "Other",

        inventoryTitle = "Stock & Inventory",
        addProduct = "Add Product",
        editProduct = "Edit Product",
        productName = "Product Name",
        quantity = "Quantity",
        unit = "Unit (kg, L, pcs, pkt)",
        purchasePrice = "Purchase Price (₹)",
        sellingPrice = "Selling Price (₹)",
        minStockLevel = "Min Alert Level",
        inStock = "In Stock",
        lowStock = "Low Stock",
        outOfStock = "Out of Stock",
        stockUnits = "units",
        searchProducts = "Search inventory...",
        adjustStock = "Adjust Stock",

        insightsTitle = "AI Business Insights",
        cashflowPredictionTitle = "AI Cash-Flow Forecast",
        expectedCashflowNextWeek = "Expected net cash flow next 7 days",
        expectedNextDay = "Tomorrow's expected cash flow",
        inventoryPredictionTitle = "Stockout Predictions",
        daysUntilStockout = "Estimated days until stockout",
        suggestedPurchase = "Suggested purchase quantity",
        financialReadinessTitle = "Financial Readiness Score",
        financialReadinessSubtitle = "Based on business health, consistency, and discipline",
        scoreNeedsImprovement = "Needs Improvement",
        scoreFair = "Fair",
        scoreGood = "Good",
        scoreStrong = "Strong",
        notEnoughData = "Not enough historical data to generate a reliable prediction. Continue recording transactions.",

        voiceEntryTitle = "Voice Transaction Entry",
        voiceListening = "Listening... Speak your sale or expense",
        voiceSpeakNow = "Tap mic and say e.g. 'Sold chai for 300 rupees' or 'Milk expense 200 rupees'",
        voiceUnderstood = "I Understood",
        askAssistant = "Bazaar Saathi AI Assistant",
        askPlaceholder = "Ask about your profit, top expense, or stock...",
        disclaimerText = "Bazaar Saathi is a financial management and analytics tool for small businesses. It is not a bank, lender, regulator, credit bureau, or loan approval system. Predictions and financial readiness scores are estimates generated from recorded business data.",
        demoDataActive = "Demo Mode (Shree Tea & Snacks)",
        loadDemoData = "Load Demo Business Data",
        clearData = "Reset to Clean Data"
    )

    val hi = StringsDefinition(
        appName = "बाज़ार साथी",
        tagline = "हर छोटे व्यवसाय के लिए स्मार्ट फाइनेंस",
        navHome = "होम",
        navSales = "बिक्री",
        navExpenses = "खर्चे",
        navInventory = "स्टॉक",
        navInsights = "अंतर्दृष्टि",
        navReports = "रिपोर्ट",
        navAssistant = "एआई साथी",
        navSettings = "सेटिंग्स",

        greetingMorning = "शुभ प्रभात",
        greetingAfternoon = "शुभ दोपहर",
        greetingEvening = "शुभ संध्या",
        todaySummary = "आज का सारांश",
        revenue = "कुल बिक्री",
        expenses = "खर्चे",
        profit = "शुद्ध मुनाफा",
        cashRevenue = "नकद बिक्री",
        upiRevenue = "यूपीआई (UPI)",
        recentTransactions = "हाल के लेन-देन",
        viewAll = "सभी देखें",
        noTransactionsYet = "अभी कोई लेन-देन दर्ज नहीं है। बिक्री जोड़ने के लिए + दबाएं या बोलें!",
        time7Days = "7 दिन",
        time30Days = "30 दिन",
        time3Months = "3 महीने",
        trendChart = "बिक्री और खर्च का रुझान",

        salesTitle = "बिक्री खाता",
        addSale = "बिक्री जोड़ें",
        editSale = "बिक्री बदलें",
        deleteSale = "हटाएं",
        saleAmount = "बिक्री राशि (₹)",
        productItem = "सामान / उत्पाद",
        paymentMethod = "भुगतान का तरीका",
        cash = "नकद (Cash)",
        upi = "ऑनलाइन (UPI)",
        category = "श्रेणी",
        description = "विवरण / नोट",
        date = "तारीख",
        save = "सुरक्षित करें",
        cancel = "रद्द करें",
        confirm = "पुष्टि करें",
        searchSales = "बिक्री खोजें...",

        expensesTitle = "खर्च खाता",
        addExpense = "खर्च जोड़ें",
        editExpense = "खर्च बदलें",
        deleteExpense = "हटाएं",
        expenseAmount = "खर्च राशि (₹)",
        searchExpenses = "खर्च खोजें...",
        rawMaterials = "कच्चा माल",
        transportation = "परिवहन/भाड़ा",
        rent = "किराया",
        electricity = "बिजली",
        packaging = "पैकिंग",
        wages = "मजदूरी",
        maintenance = "मरम्मत",
        other = "अन्य",

        inventoryTitle = "स्टॉक और माल",
        addProduct = "सामान जोड़ें",
        editProduct = "सामान बदलें",
        productName = "सामान का नाम",
        quantity = "मात्रा",
        unit = "इकाई (किग्रा, ली, पैकेट, नग)",
        purchasePrice = "खरीद मूल्य (₹)",
        sellingPrice = "बिक्री मूल्य (₹)",
        minStockLevel = "न्यूनतम चेतावनी स्तर",
        inStock = "स्टॉक में है",
        lowStock = "कम स्टॉक",
        outOfStock = "स्टॉक खत्म",
        stockUnits = "यूनिट",
        searchProducts = "स्टॉक खोजें...",
        adjustStock = "स्टॉक बदलें",

        insightsTitle = "एआई व्यावसायिक अंतर्दृष्टि",
        cashflowPredictionTitle = "एआई नकदी प्रवाह अनुमान",
        expectedCashflowNextWeek = "अगले 7 दिनों का संभावित नकदी प्रवाह",
        expectedNextDay = "कल का अनुमानित नकदी प्रवाह",
        inventoryPredictionTitle = "स्टॉक खत्म होने का अनुमान",
        daysUntilStockout = "स्टॉक खत्म होने में अनुमानित दिन",
        suggestedPurchase = "अनुशंसित खरीद मात्रा",
        financialReadinessTitle = "वित्तीय तैयारी स्कोर",
        financialReadinessSubtitle = "व्यापार स्वास्थ्य और नियमितता के आधार पर",
        scoreNeedsImprovement = "सुधार की आवश्यकता",
        scoreFair = "संतोषजनक",
        scoreGood = "अच्छा",
        scoreStrong = "मजबूत",
        notEnoughData = "सटीक भविष्यवाणी के लिए पर्याप्त डेटा नहीं है। नियमित लेन-देन दर्ज करते रहें।",

        voiceEntryTitle = "आवाज़ से लेन-देन जोड़ें",
        voiceListening = "सुन रहे हैं... अपनी बिक्री या खर्च बोलें",
        voiceSpeakNow = "माइक दबाकर बोलें, जैसे: 'पाँच सौ रुपये की बिक्री हुई' या 'दूध का दो सौ रुपये खर्च हुआ'",
        voiceUnderstood = "मैंने यह समझा",
        askAssistant = "बाज़ार साथी एआई सलाहकार",
        askPlaceholder = "मुनाफे, खर्च या स्टॉक के बारे में पूछें...",
        disclaimerText = "बाज़ार साथी छोटे व्यवसायों के लिए एक वित्तीय प्रबंधन और विश्लेषण उपकरण है। यह कोई बैंक, ऋणदाता, नियामक, क्रेडिट ब्यूरो या ऋण अनुमोदन प्रणाली नहीं है। पूर्वानुमान और स्कोर केवल दर्ज किए गए डेटा के आधार पर अनुमान हैं।",
        demoDataActive = "डेमो मोड (श्री टी & स्नैक्स)",
        loadDemoData = "डेमो डेटा लोड करें",
        clearData = "साफ़ डेटा पर रीसेट करें"
    )

    val mr = StringsDefinition(
        appName = "बाजार साथी",
        tagline = "प्रत्येक लहान व्यवसायासाठी स्मार्ट फायनान्स",
        navHome = "मुख्य पान",
        navSales = "विक्री",
        navExpenses = "खर्च",
        navInventory = "इन्व्हेंटरी",
        navInsights = "अंतर्दृष्टी",
        navReports = "अहवाल",
        navAssistant = "एआय साथी",
        navSettings = "सेटिंग्ज",

        greetingMorning = "शुभ प्रभात",
        greetingAfternoon = "शुभ दुपार",
        greetingEvening = "शुभ संध्याकाळ",
        todaySummary = "आजचा सारांश",
        revenue = "एकूण विक्री",
        expenses = "एकूण खर्च",
        profit = "निव्वळ नफा",
        cashRevenue = "रोख विक्री",
        upiRevenue = "यूपीआय (UPI)",
        recentTransactions = "अलीकडील व्यवहार",
        viewAll = "सर्व पहा",
        noTransactionsYet = "अद्याप कोणताही व्यवहार नोंदवलेला नाही. व्यवहार जोडण्यासाठी + दाबा किंवा बोला!",
        time7Days = "7 दिवस",
        time30Days = "30 दिवस",
        time3Months = "3 महिने",
        trendChart = "विक्री आणि खर्चाचा कल",

        salesTitle = "विक्री वही",
        addSale = "विक्री जोडा",
        editSale = "विक्री बदला",
        deleteSale = "हटवा",
        saleAmount = "विक्री रक्कम (₹)",
        productItem = "वस्तू / उत्पादन",
        paymentMethod = "पेमेंट पद्धत",
        cash = "रोख (Cash)",
        upi = "ऑनलाईन (UPI)",
        category = "प्रवर्ग",
        description = "तपशील / नोंद",
        date = "तारीख",
        save = "जतन करा",
        cancel = "रद्द करा",
        confirm = "पुष्टी करा",
        searchSales = "विक्री शोधा...",

        expensesTitle = "खर्च वही",
        addExpense = "खर्च जोडा",
        editExpense = "खर्च बदला",
        deleteExpense = "हटवा",
        expenseAmount = "खर्च रक्कम (₹)",
        searchExpenses = "खर्च शोधा...",
        rawMaterials = "कच्चा माल",
        transportation = "वाहतूक",
        rent = "भाडे",
        electricity = "वीज",
        packaging = "पॅकिंग",
        wages = "मजुरी",
        maintenance = "दुरुस्ती",
        other = "इतर",

        inventoryTitle = "स्टॉक आणि इन्व्हेंटरी",
        addProduct = "वस्तू जोडा",
        editProduct = "वस्तू बदला",
        productName = "वस्तूचे नाव",
        quantity = "प्रमाण / नग",
        unit = "एकक (किलो, ली, पाकीट, नग)",
        purchasePrice = "खरेदी किंमत (₹)",
        sellingPrice = "विक्री किंमत (₹)",
        minStockLevel = "किमान साठा इशारा",
        inStock = "स्टॉकमध्ये आहे",
        lowStock = "कमी साठा",
        outOfStock = "साठा संपला",
        stockUnits = "नग",
        searchProducts = "स्टॉक शोधा...",
        adjustStock = "साठा बदला",

        insightsTitle = "एआय व्यावसायिक अंतर्दृष्टी",
        cashflowPredictionTitle = "एआय रोख प्रवाह अंदाज",
        expectedCashflowNextWeek = "पुढील 7 दिवसांचा अंदाजित रोख प्रवाह",
        expectedNextDay = "उद्याचा अंदाजित रोख प्रवाह",
        inventoryPredictionTitle = "साठा संपण्याचा अंदाज",
        daysUntilStockout = "साठा संपण्यासाठी अंदाजित दिवस",
        suggestedPurchase = "शिफारस केलेली खरेदी मात्रा",
        financialReadinessTitle = "आर्थिक तयारी धावसंख्या",
        financialReadinessSubtitle = "व्यवसाय आरोग्य आणि शिस्तीवर आधारित",
        scoreNeedsImprovement = "सुधारणा आवश्यक",
        scoreFair = "समाधानकारक",
        scoreGood = "चांगले",
        scoreStrong = "उत्कृष्ट",
        notEnoughData = "अचूक अंदाजासाठी पुरेसा इतिहास उपलब्ध नाही. नियमित व्यवहार नोंदवणे सुरू ठेवा.",

        voiceEntryTitle = "आवाजाने व्यवहार जोडा",
        voiceListening = "ऐकत आहे... आपली विक्री किंवा खर्च बोला",
        voiceSpeakNow = "माइक दाबा आणि बोला, उदा: 'पाचशे रुपयांची विक्री झाली' किंवा 'दूधासाठी तीनशे रुपये खर्च झाले'",
        voiceUnderstood = "मला समजले",
        askAssistant = "बाजार साथी एआय मार्गदर्शक",
        askPlaceholder = "नफा, खर्च किंवा साठ्याबद्दल विचारा...",
        disclaimerText = "बाजार साथी हे लहान व्यवसायांसाठी आर्थिक व्यवस्थापन आणि विश्लेषण साधन आहे. ही कोणतीही बँक, सावकार, नियामक, क्रेडिट ब्युरो किंवा कर्ज मंजुरी संस्था नाही. अंदाज आणि स्कोअर केवळ नोंदवलेल्या डेटावर आधारित अंदाज आहेत.",
        demoDataActive = "डेमो मोड (श्री टी & स्नॅक्स)",
        loadDemoData = "डेमो डेटा भरा",
        clearData = "नवीन स्वच्छ डेटा सुरू करा"
    )

    fun get(language: AppLanguage): StringsDefinition {
        return when (language) {
            AppLanguage.ENGLISH -> en
            AppLanguage.HINDI -> hi
            AppLanguage.MARATHI -> mr
        }
    }
}
